### ISSUE TITLE
望能努力创新

### ISSUE THREAD

**Issue by fananwu** [hustcc/php-file-cache#1]
看了代码，好像还是碎片化的缓存方式，数据不多可以，但是数据量大 liunx下 磁盘inode用完的情况我想朋友你没有遇到过吧.望能开展出新思路！

**Comment by hustcc** [comment]
主要用于一些sql缓存，比如统计…或者一些需要缓存的变量，比如一些开放平台的token…如果是用于大量的数据缓存，还是用redis吧…如果非要文件缓存，sqlite也不错，不过效果估计并不好…
